# Numpy

In [1]:
import numpy as np

In [21]:
np.random.seed(0)
a = np.array([1,2,3,4,5])
b = np.random.randint(0, 10, (2, 5))
a

array([1, 2, 3, 4, 5])

Fill Data with zeros, ones, full, arrange and lindspace

In [4]:
c = np.zeros((1, 10), int)
c


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [5]:
d = np.ones((1, 10), int)
d


array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [6]:
d = np.full((1, 10), 5, float)
d
# np.full(shape, fill_value, dtype)


array([[5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [9]:
e = np.arange(0, 5, 1)
e

array([0, 1, 2, 3, 4])

In [13]:
g = np.linspace(0, 5, 4)
g


array([0.        , 1.66666667, 3.33333333, 5.        ])

Indexing and Slicing

In [22]:
print(a[0]) 
print(b[1][2]) 

print(a[0:2])
print(b[0:2,0:2]) 

1
5
[1 2]
[[5 0]
 [9 3]]


Operator

In [23]:
print(a+1)
print(a-1)
print(a*2)
print(a/2)
print(a%2)
print(a**2)
print(a<3)

[2 3 4 5 6]
[0 1 2 3 4]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]
[1 0 1 0 1]
[ 1  4  9 16 25]
[ True  True False False False]
